import css from "../About/About.module.css";
import addSharp from "../../assets/add-sharp.svg";
import heroAPE2 from "../../assets/heroAPE2.png";
import { motion } from "framer-motion";

const About = ({ setSelectedPage }) => {
  return (
    <section id="about" className={css.section}>
           <motion.div
        // className="mx-auto w-5/6 items-center justify-center md:flex md:h-5/6"
        onViewportEnter={() => setSelectedPage("about")}
      >
      <div className={css.textBox}>
        <h1 className={css.title}>
          a Story that started with <span>one simple <br/>ape</span>
        </h1>

        <p className={css.textRight}>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <br />
          YACHT
        </p>
      </div>
      <div className={css.textBoxLeft}>
        <img className={css.textLeftImg} src={addSharp} alt="icon cross" />
        <p className={css.textLeft}>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
      </div>

      <div>
        <div className={css.boxImg}>
          <img className={css.heroImg} src={heroAPE2} alt="hero Ape 2" />
        </div>
      </div>
      <div className={css.bannerBackground}>
        <div className={css.banner}>
          <p className={css.textBanner}>Destroy stereotypes</p>
          <img className={css.textImg} src={addSharp} alt="icon cross" />
          <p className={css.textBanner}>HAVE NO LIMITS</p>
          <img className={css.textImg} src={addSharp} alt="icon cross" />
          <p className={css.textBanner}>Break rules</p>
          <img className={css.textImg} src={addSharp} alt="icon cross" />
        </div>
      </div>
      </motion.div>
    </section>
  );
};

export default About;
